# Generated by Django 3.1.7 on 2021-02-25 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210224_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 25, 13, 27, 24, 243594, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
